#name for valedation
name = "hello"

# setting
data_base_path = "paht/to/data/base"
#updateble
url = "https://api.hypixel.net/v2/skyblock/bazaar"
table_name = "test"
step_rate = 30
update_rate = 120


